Full Traceback (most recent call last):
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/__init__.py", line 619, in snakemake
    workflow.include(
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/workflow.py", line 1206, in include
    exec(compile(code, snakefile.get_path_or_uri(), "exec"), self.globals)
  File "/home/ayla/Dropbox/Ancient genotypes/DNA_variant_calling_GATK_Snakemake/workflow/Snakefile", line 1, in <module>
    configfile: '../config/config.yaml'
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/workflow.py", line 1278, in configfile
    raise WorkflowError(
snakemake.exceptions.WorkflowError: Workflow defines configfile ../config/config.yaml but it is not present or accessible.

WorkflowErrorin line 1 of /home/ayla/Dropbox/Ancient genotypes/DNA_variant_calling_GATK_Snakemake/workflow/Snakefile:
Workflow defines configfile ../config/config.yaml but it is not present or accessible.
  File "/home/ayla/Dropbox/Ancient genotypes/DNA_variant_calling_GATK_Snakemake/workflow/Snakefile", line 1, in <module>
